name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  freezed_annotation: ^2.1.0

  flutter:
    sdk: flutter
  dartz: ^0.10.1

dev_dependencies:
  flutter_lints: 2.0.1
  freezed: ^2.1.0+1
  json_serializable:
  lint: ^1.5.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
